### ISSUE TITLE
[Bug]: If I click on deposit for USDC it is trying to deposit USDT.t and if I click on deposit for USDT it is trying to deposit USDC.t

### ISSUE THREAD

**Issue by v9hstk** [0xHashstack/open-ui#8]
<img width="835" alt="Screenshot 2022-01-12 at 8 42 22 PM" src="https://user-images.githubusercontent.com/7675855/149167276-84633c38-dd4a-45da-ab8c-8eb92bb20ee2.png">

**Comment by MPankajArun** [comment]
Fixed. Pushed the fix in skote-ui branch.
